/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jujubalaka;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author laila
 */
public class cadastrar extends javax.swing.JFrame {

    String[][] matrix = new String[10][3];
    int i = 0;

    public cadastrar() {
        initComponents();
        lblobrignome.setVisible(false);
        lblobrigcid.setVisible(false);
        lblobrigest.setVisible(false);
        setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblobrignome = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcidade = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        lblobrigcid = new javax.swing.JLabel();
        lblobrigest = new javax.swing.JLabel();
        bntcadastrar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblobrignome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblobrignome.setForeground(new java.awt.Color(255, 255, 0));
        lblobrignome.setText("*Campo obrigratório*");
        jPanel1.add(lblobrignome, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 130, -1));

        lblnome.setBackground(new java.awt.Color(255, 255, 255));
        lblnome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnome.setForeground(new java.awt.Color(255, 255, 255));
        lblnome.setText("NOME:");
        jPanel1.add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, -1));

        lblcidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblcidade.setForeground(new java.awt.Color(255, 255, 255));
        lblcidade.setText("CIDADE:");
        jPanel1.add(lblcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        lblestado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblestado.setForeground(new java.awt.Color(255, 255, 255));
        lblestado.setText("ESTADO:");
        jPanel1.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 460, 40));

        txtcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 460, 40));
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 460, 40));

        lblobrigcid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblobrigcid.setForeground(new java.awt.Color(255, 255, 51));
        lblobrigcid.setText("*Campo obrigratório*");
        jPanel1.add(lblobrigcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 150, 20));

        lblobrigest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblobrigest.setForeground(new java.awt.Color(255, 255, 51));
        lblobrigest.setText("*Campo obrigratório*");
        jPanel1.add(lblobrigest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 130, 20));

        bntcadastrar.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        bntcadastrar.setForeground(new java.awt.Color(181, 135, 34));
        bntcadastrar.setText("CADASTRAR");
        bntcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bntcadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 150, 30));

        btnimprimir.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnimprimir.setForeground(new java.awt.Color(163, 121, 43));
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/jujubalaka/WhatsApp Image 2024-09-27 at 10.26.39.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidadeActionPerformed

    private void bntcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcadastrarActionPerformed
        //PEGAR OS DADOS INSERIDOS.
        String nome = txtnome.getText();
        String cidade = txtcidade.getText();
        String estado = txtestado.getText();
        // VERIFICAR SE TODOS OS CAMPOS ESTÃO PREENCHIDOS.
        boolean havErro = false;
        if (nome.isEmpty()) {
            lblobrignome.setVisible(true);
            txtnome.requestFocus(); // DEFINIR O FOCO NA VARIÁVEL
            havErro = true;
        } else {
            lblobrignome.setVisible(false);
        }

        if (cidade.isEmpty()) {
            lblobrigcid.setVisible(true);
            if (!havErro) {
                txtcidade.requestFocus();
            }
            havErro = true;
        } else {
            lblobrigcid.setVisible(false);
        }

        if (estado.isEmpty()) {
            lblobrigest.setVisible(true);
            if (!havErro) {
                txtestado.requestFocus();
            }
            havErro = true;
        } else {
            lblobrigest.setVisible(false);
        }

        if (havErro) {
            return;
        }

        if (i < 10) {
            // ARMAZENAR AS INFORMAÇÕES
            matrix[i][0] = nome;
            matrix[i][1] = cidade;
            matrix[i][2] = estado;
            i++;
            txtnome.setText("");
            txtcidade.setText("");
            txtestado.setText("");
        }else{
        JOptionPane.showMessageDialog(null, "Todas as vagas ja foram preenchidas!!! \n Aperte imprimir para ter acesso a lista.");
        }
        
    }//GEN-LAST:event_bntcadastrarActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        //CHAMAR O JFRAME IMPRIMIR
        new imprimir(matrix).setVisible(true);
        new cadastrar().setVisible(false);
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntcadastrar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblobrigcid;
    private javax.swing.JLabel lblobrigest;
    private javax.swing.JLabel lblobrignome;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
